config/routes.rb
Rails.application.routes.draw do
  
  if !Rails.env.development?
    match "*path" => redirect("https://matching.e-nable.me/%{path}"), :constraints => { :protocol => "http://" }, :via => [:get, :post]
    match "*path" => redirect("https://matching.e-nable.me/%{path}"), :constraints => { :subdomain => "" }, :via => [:get, :post]
  end
  
  devise_for :members, controllers: {registrations: 'members/registrations', sessions: 'members/sessions'}

  devise_scope :member do
    root to: "devise/sessions#new"
    get "members/sign_out", to: 'devise/sessions#destroy'
    get "members/:id/edit", to: 'members/registrations#edit'
  end
    
  devise_scope :offer do
    post 'offers/:id/accept', to: 'offers#accept', as: 'offers_accept'
    post 'offers/:id/decline', to: 'offers#decline', as: 'offers_decline'
  end
    
  devise_scope :request do
    get 'requests/mine', to: 'requests#mine'
    get 'requests/:id/complete', to: 'requests#complete'
  end
  
  devise_scope :chapter do
    get 'chapters/:id/claim', to: 'chapters#claim'
    get 'chapters/:id/claimsend', to: 'chapters#claimsend'
    get 'chapters/agree', to: 'chapters#agree'
    get 'chapters/:id/review', to: 'chapters#review'
    post 'chapters/:id/approve', to: 'chapters#approve'
    post 'chapters/:id/reject', to: 'chapters#reject'
  end

  resources :members
  resources :requests
  resources :offers
  resources :devices
  resources :messages
  resources :chapters
  resources :notices
  resources :reviews

  get 'states/:country', to: 'application#states'
  get 'cities/:state', to: 'application#cities'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/device.rb
class Device < ApplicationRecord
  has_many :requests, dependent: :nullify
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  rescue_from ActiveRecord::RecordNotFound do
    flash[:notice] = "That device is not found"
    redirect_to root_path
  end

  # GET /devices
  # GET /devices.json
  def index
    if !current_member.admin?
      flash[:notice] = "You are not permitted to edit devices."
      redirect_to member_path(current_member)
    else
      @devices = Device.all
    end
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    if !current_member.admin?
      flash[:notice] = "You are not permitted to add devices."
      redirect_to member_path(current_member)
    else
      @device = Device.new
    end
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(title: params['title'])

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(title: params['title'])
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.fetch(:device, {})
    end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= form_for(device) do |f| %>
  <% if device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<div class="sectionHeader" style="margin-bottom: 0;">Edit Device</div>
	<%= form_tag(@device, method: "PATCH") do %>	
	
	<div class="card" style="margin-bottom: 10px; cursor: default; display: block;">
		<div class="cardLine" style="font-style: italic; display: block;"> Visit <a href="http://enablingthefuture.org/which-design/" target="_new" style="display: inline;">the e-NABLE website</a> to learn about the different types of devices available</div>
		<div class="cardLine"><div class="cardHead">Name</div><div class="cardData"><%= text_field_tag(:title, @device.title, class: 'messageBox', style: 'height: 1em;') %></div></div>	
		<div class="actions"><%= submit_tag "Update Device", class: 'clicky' %></div>
	</div>	
	<% end %>
</div>

app/views/devices/index.html.erb
<div class="sectionHeader" style="margin-bottom: 0px;">Devices</div>

<div class="cardContainer">
    <% @devices.each do |device| %>	
    	<a href="<%= url_for device %>">
		<div class="card">
			<div class="cardCol">TODO Photo</div>
			<div class="cardCol" style="max-width: unset;"><%= device.title %></div>
			<div class="cardCol" style="min-width: 3em;"><%= link_to 'Edit', edit_device_path(device) %></div>
			<div class="cardCol" style="min-width: 4em;"><%= link_to 'Delete', device, method: :delete, data: { confirm: 'Are you sure?' } %></div>
		</div>
		</a>
	<% end %>	
</div><br>
<%= link_to 'New Device', new_device_path, class: 'clicky' %>

app/views/devices/new.html.erb
<div>
	<%= form_tag(devices_path, method: "POST") do %>	
	
	<div class="card" style="margin-bottom: 10px; cursor: default; display: block;">
		<div class="cardLine" style="font-style: italic; display: block;"> Visit <a href="http://enablingthefuture.org/which-design/" target="_new" style="display: inline;">the e-NABLE website</a> to learn about the different types of devices available</div>
		<div class="cardLine"><div class="cardHead">Name</div><div class="cardData"><%= text_field_tag(:title, '', class: 'messageBox', style: 'height: 1em;') %></div></div>	
		<div class="actions"><%= submit_tag "Add Device", class: 'clicky' %></div>
	</div>	
	<% end %>
</div>

app/views/devices/show.html.erb
<div>
	<div class="card" style="margin-bottom: 10px; cursor: default; display: block;">
		<div class="cardLine"><div class="cardHead">Name</div><div class="cardData"><%= @device.title %></div></div>
	</div>

	<div style="margin-top: 10px;">
		<% if current_member.admin? %>
			<%= link_to("Edit Device", edit_device_path(@device), class: "clicky") %>
		<% end %>
	</div>
</div>