config/routes.rb
Rails.application.routes.draw do
  
  if !Rails.env.development?
    match "*path" => redirect("https://matching.e-nable.me/%{path}"), :constraints => { :protocol => "http://" }, :via => [:get, :post]
    match "*path" => redirect("https://matching.e-nable.me/%{path}"), :constraints => { :subdomain => "" }, :via => [:get, :post]
  end
  
  devise_for :members, controllers: {registrations: 'members/registrations', sessions: 'members/sessions'}

  devise_scope :member do
    root to: "devise/sessions#new"
    get "members/sign_out", to: 'devise/sessions#destroy'
    get "members/:id/edit", to: 'members/registrations#edit'
  end
    
  devise_scope :offer do
    post 'offers/:id/accept', to: 'offers#accept', as: 'offers_accept'
    post 'offers/:id/decline', to: 'offers#decline', as: 'offers_decline'
  end
    
  devise_scope :request do
    get 'requests/mine', to: 'requests#mine'
    get 'requests/:id/complete', to: 'requests#complete'
  end
  
  devise_scope :chapter do
    get 'chapters/:id/claim', to: 'chapters#claim'
    get 'chapters/:id/claimsend', to: 'chapters#claimsend'
    get 'chapters/agree', to: 'chapters#agree'
    get 'chapters/:id/review', to: 'chapters#review'
    post 'chapters/:id/approve', to: 'chapters#approve'
    post 'chapters/:id/reject', to: 'chapters#reject'
  end

  resources :members
  resources :requests
  resources :offers
  resources :devices
  resources :messages
  resources :chapters
  resources :notices
  resources :reviews

  get 'states/:country', to: 'application#states'
  get 'cities/:state', to: 'application#cities'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :member # id of recipient
  has_one :device #device they requested

  geocoded_by :map_address   # can also be an IP address
  after_validation :geocode, if: ->(obj){ obj.shipping_address.present? and obj.shipping_address_changed? }          # auto-fetch coordinates
  validates :side, :shipping_address, presence: true

  def open_offer(mem)
    return !Offer.where(member_id: mem.id, request_id: self.id).empty?
  end
  
  def accepted_offer(mem)
    return !Offer.where(member_id: mem.id, request_id: self.id, stage: 'Accepted').empty?
  end

  def map_address
    #might be better to find city, country from shipping address so geocode is not on someone's house.  For now, will restrict zoom level of map, but may be able to get geocode from script.
    return self.shipping_address
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController 
  before_action :set_request, only: [:show, :edit, :update, :destroy, :complete]

  rescue_from ActiveRecord::RecordNotFound do
    flash[:notice] = "That request is not found"
    redirect_to root_path
  end
  
  def index
    @requests = Request.where("stage != 'Completed'").order('created_at ASC')
    @match = true
  end

  def new
    @request = Request.new  
  end
  
  def create
    @request = Request.create(
      device_id: params[:device][:id], 
      side: params[:side], 
      member_id: current_member.id, 
      shipping_address: params[:shipping_address],
      colors: params[:colors],
      measurements: params[:measurements],
      photos: params[:photos]
    )
    
    if @request.valid? 
      Message.new do |m|
        m.from = Member.find_by(first_name: "System").id
        m.to = @request.member_id
        m.content = "You created <a href=\"#{Rails.application.routes.url_helpers.request_path @request.id}\">Request ##{@request.id.to_s}</a>."
        m.save  
      end
      flash[:notice] = "Request successfully created."
      redirect_to @request
    else
      render :new
    end
  end

  def show
    @requests = Request.all
    @match = true
  end
  
  def edit
    if @request.member_id == current_member.id || current_member.admin?
    else
      flash[:notice] = "You are not permitted to edit this request."
      redirect_to @request
    end  
  end
  
  def mine
    @requests = Request.where(member_id: current_member.id).order('created_at DESC')
  end
  
  def update
    if @request.update(colors: params[:colors], measurements: params[:measurements], photos: params[:photos], device_id: params[:device][:id], side: params[:side], evidence: params[:evidence], shipping_address: params[:shipping_address])
        redirect_to @request, notice: 'Request was successfully updated.'
    else
        render :edit
    end
  end
  
  def complete
    if (@request.member_id == current_member.id || current_member.admin?) && @request.stage!="Completed"
    else
      flash[:notice] = "You are not permitted to mark this request as complete."
      redirect_to @request
    end 
  end

#Ruby auto-routes to this from the complete.html.erb form ; could change in routes.rb later  
def destroy 
    if params[:evidence].blank?
      @request.errors.add(:evidence, "Please provide evidence before marking this request complete.")
      render :complete
    else
      if @request.update(stage: "Completed", evidence: params[:evidence])
        @offers = Offer.where(request_id: @request.id)
        @offers.each do |off|
            if off.stage == 'Offered'
              off.update stage: 'Abandoned'
            
              Message.new do |m|
                m.from = Member.find_by(first_name: "System").id
                m.to = off.member_id
                m.content = "<a href='#{Rails.application.routes.url_helpers.member_path @request.member_id}'>#{Member.find(@request.member_id).first_name}</a> closed <a href='#{Rails.application.routes.url_helpers.request_path @request.id}'>Request ##{@request.id.to_s}</a>, so your offer was abandoned."
                m.save  
              end
            end 
            
            if off.stage == 'Accepted'
              off.update stage: 'Completed' 
           
              Message.new do |m|
                m.from = Member.find_by(first_name: "System").id
                m.to = off.member_id
                m.content = "Congratulations!  <a href='#{Rails.application.routes.url_helpers.member_path @request.member_id}'>#{Member.find(@request.member_id).first_name}</a> marked <a href='#{Rails.application.routes.url_helpers.request_path @request.id}'>Request ##{@request.id.to_s}</a> as complete.  Please click <a href='#{Rails.application.routes.url_helpers.new_review_path}?for=#{@request.member_id.to_s}'>here</a> to leave a review for #{Member.find(@request.member_id).first_name}."
                m.save  
              end
              
              Message.new do |m|
                m.from = Member.find_by(first_name: "System").id
                m.to = @request.member_id
                m.content = "You closed <a href='#{Rails.application.routes.url_helpers.request_path @request.id}'>Request ##{@request.id.to_s}</a>.  Please click <a href='#{new_review_path}?for=#{off.member_id.to_s}'>here</a> to leave a review for #{Member.find(off.member_id).first_name}."
                m.save  
              end
            end
        end
        
        flash[:notice] = "Request and associated offers closed"
        
        redirect_to requests_path
        else
          render :complete
      end
    end
end
  
private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/complete.html.erb
<script> sweetAlert({title: "We Need Your Help!", text: "Before you mark this request as complete, please take a few minutes to tell us about your experience.  Your feedback helps us improve.  We would especially like to know if there were any problems.", type: 'warning', confirmButtonColor: '#59d2ff'}); </script>

<%= form_error_messages(@request) %>

<div class="noteblock" style="margin-bottom: 35px; padding: 15px; margin-top: 20px;">
Please take the survey <a href='https://www.surveymonkey.com/r/XVFT8CY' target="_new">here</a> and enter Request #<%=@request.id.to_s %>.
</div>

<%= form_tag(url_for(controller: 'requests', action: 'destroy'), method: "DELETE", class: "loginfield") do %>
	<%= label_tag('Evidence of Completion') %>
	<div style="width: 450px;">
		<div class="tooltip"><span class="tooltiptext">We require evidence that the device has been successfuly delivered to the recipient.  Please provide links to photos or other evidence of completion.</span><%= text_area_tag(:evidence, @request.evidence) %></div>
		<% msg = "Thank you for providing us your valuable feedback.  If you did not have time today, you can always provide feedback <a href='https://www.surveymonkey.com/r/XVFT8CY' target='_new'>here</a>" %>
		<%= submit_tag "Mark Request #" << @request.id.to_s << " Complete", class: 'loginaction', onclick: "if (document.getElementById('evidence').value != '') {sweetAlert({title: 'Thank You!!', text: \""<<msg<<"\", type: 'success', html: true, confirmButtonColor: '#59d2ff'});}" %>
	</div>
<% end %>

app/views/requests/edit.html.erb
<%= form_error_messages(@request) %>
<div style="position: relative;">
<div class="logincontainer" style="position: relative;">
	<div class="sectionHeader" style="margin-bottom: 20px;">Edit Request</div>

<%= form_tag(url_for(@request), method: "PUT", class: 'loginfield') do %>	
	<%= label_tag("Device") %>
	<div class="loginfield" style="margin-left: 15px;"><%= collection_select(:device, :id, Device.all, :id, :title, selected: @request.device_id) %></div>
	
	<%= label_tag("Side") %>
	<div id="side" style="margin-left:15px; margin-bottom: 10px; margin-top: 5px; display: flex;">
		<div class="loginfield">
			<%= label_tag(:side, "Left") %>
			<%= radio_button_tag(:side, "Left", (@request.side == "Left")) %>
		</div>
		<div class="loginfield">
			<%= label_tag(:side, "Right") %>
			<%= radio_button_tag(:side, "Right", (@request.side == "Right")) %>
		</div>
	</div>
	
	<%= label_tag(:shipping_address) %>
	<div class="loginfield"><%= text_area_tag(:shipping_address, @request.shipping_address, class: 'shippingAdd')%></div>
	<%= label_tag(:colors) %>
	<div class="loginfield"><%= text_area_tag(:colors, @request.colors) %></div>
	<%= label_tag(:measurements) %>
	<div class="loginfield"><%= text_area_tag(:measurements, @request.measurements) %></div>
			<div class="cardData" style="position: relative; left: 100px; top: -120px;">
					<a href="" id="big" target="_new"><img src="" id="meas" style="width: 400px; position: absolute;"/></a>
			</div>			
	<%= label_tag('Photos/Video') %>
	<div class="loginfield"><%= text_area_tag(:photos, @request.photos) %></div>
	<%= label_tag('Evidence of Completion') %>
	<div class="loginfield"><div class="tooltip"><span class="tooltiptext">Once the device has been successfuly delivered to the recipient, please provide links to photos or other evidence of completion.</span><%= text_area_tag(:evidence, @request.evidence) %></div></div>
	</div>	
	
	<div class="loginfield">
		<%= submit_tag "UPDATE REQUEST", class: 'loginaction' %>
	</div>
<% end %>

</div>
</div>

app/views/requests/index.html.erb
<div id="map" class="mapdiv"></div>

<div class="submitButton" style="margin-bottom: 50px; margin-top: 25px;">
	<div style="margin: auto;"><%= link_to "SUBMIT NEW REQUEST", new_request_path %></div>
</div>

<% if current_member.admin? %>
	<div class="sectionHeader" style="margin-bottom: 0;">All Requests (because you're an admin)</div>
	<%= render "layouts/requests"%>
<% else %>
	<div class="sectionHeader" style="margin-bottom: 0;">Open Requests</div>
	<% @requests = @requests.where(stage: "Open") %>
	<%= render "layouts/requests" %>
<% end %>


<script>
  $(function(handler) {
var LatLngList = [],
    latlngbounds = new google.maps.LatLngBounds();

LatLngList.forEach(function(latLng){
   latlngbounds.extend(latLng);
});
	
	handler = Gmaps.build('Google');
	handler.buildMap({ 
		provider: {
	    	maxZoom: 10, 
	    	mapTypeControl: false,
	    	streetViewControl: false},
    	internal: {id: 'map' }}, 
    	function(){
	    markers = handler.addMarkers([
	    <% @requests.each do |req| %>
	    {
	    	lat: <%= req.latitude%>, 
	    	lng: <%= req.longitude%>,
	    	infowindow: '<div class="infowin"> \
		    			<b>Submitted Date:</b> <%= req.created_at %> <br> \
		    			<b>By: </b> <%= Member.find(req.member_id).full_name %> <br> \
		    			<b>Device:</b> <%= Device.find(req.device_id).title %> <br> \
		    			<b>Side:</b> <%= req.side %> <br> \
		    			<%= link_to("View Request", url_for(req), class: "clicky") %></div>'
	    },
	    <% end %>
	  ]);
	  handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
	  

	});	
  });
</script>

app/views/requests/mine.html.erb
<!-- @requests has mine loaded already -->
<div class="sectionHeader" style="margin-bottom: 0;">Requests by <%= current_member.first_name %></div>
<%= render "layouts/requests"%>

<% if current_member.admin? %>
	<div class="sectionHeader" style="margin-bottom: 0; margin-top: 40px;">All Requests (because you are admin)</div>
	<% @requests = Request.all.order('created_at DESC') %>
	<% @match = true %>
	<%= render "layouts/requests"%>
<% end %>

app/views/requests/new.html.erb
<%= form_error_messages(@request) %>
<div class="sectionHeader" style="margin-bottom: 0;">New Request</div>
<div>
	<div class="card" id="note" style="margin-bottom: 20px; white-space: normal; display: block;">
		<div style="margin-bottom: 20px; cursor: auto;"> We strongly advise all recipients to consult a doctor or prosthetist before using an e-NABLE device.  We also recommend that recipients consult an occupational or physical therapist after receiving the device.</div>
		<div class="loginaction" style="display: flex; align-items: center;" onclick="document.getElementById('req').style.visibility='visible';var e = document.getElementById('note'); e.parentNode.removeChild(e);"><div style="margin: auto;">I Understand</div></div>
	</div>
	
	<style>.cardData {width: 50%;} label {display: inline-block;}</style>
	<%= form_tag(requests_path, method: "POST", class: "loginfield") do %>	
	
	<div class="card" id="req" style="visibility: hidden; margin-bottom: 10px; cursor: default; display: block;">
		<div class="cardLine"><div class="cardHead">*Device</div><div class="cardData"><%= collection_select(:device, :id, Device.all, :id, :title) %></div></div>
		<div class="cardLine"><div class="cardHead">*Side</div>
			<div class="cardData" id="side">
				<%= label_tag(:side, "Left") %>
				<input type="radio" name="side" id="side_Left" value="Left" onclick="document.getElementById('meas').src='/intakeLeft.png';document.getElementById('big').href='/intakeLeft.png';">
				<%= label_tag(:side, "Right") %>
				<input type="radio" name="side" id="side_Right" value="Right" onclick="document.getElementById('meas').src='/intakeRight.png';document.getElementById('big').href='/intakeRight.png';">
			</div>
		</div>
		<div class="cardLine"><div class="cardHead">Colors</div><div class="cardData"><%= text_area_tag(:colors, 'Describe what style and colors you would like.  Do you want any special designs, team logos or themes?', class: 'messageBox', style: 'height: 40px;') %></div></div>
		<div class="cardLine"><div class="cardHead">*Shipping Address</div><div class="tooltip" style="width: 50%;"><div class="cardData" style="width: 100%;"><span class="tooltiptext" style="width: 300px;">This is the address to ship the device to.  Nobody can see this address except the person you choose to build the device. If you do not want to use your personal address, you can send it to a nearby <a href='<%= chapters_path %>' target='_blank' style='color: white;'>e-NABLE chapter</a> or a FedEx/DHL office.  Your post office may also accept 'General Delivery' or 'Poste Restante' deliveries on your behalf.</span> <%= text_area_tag(:shipping_address, '', class: 'messageBox')%></div></div></div>

		<div class="cardLine" style="font-style: italic; display: block; margin-top: 40px;"> Use <a href="https://docs.google.com/document/d/1vWDoGMzwca5G__8-2kdTte2w3qs8-h_Nv7PmFLszn4w" target="_new" style="display: inline;">this Guide</a> to learn about taking measurements and photos</div>
		<div class="cardLine"><div class="cardHead">Measurements</div>
			<div class="cardData"><%= text_area_tag(:measurements, 'A= B= C= ... G= or provide a link to a photo or document with the measurements.  A volunteer can help you take required measurements once you have accepted their offer.', class: 'messageBox', style: 'height: 55px;') %></div>
			<div class="" style="position: relative; left: 100px; top: -100px;">
					<a href="" id="big" target="_new"><img src="" id="meas" style="width: 400px; position: absolute;"/></a>
			</div>			
		</div>
		<div class="cardLine"><div class="cardHead">Photos/Video</div><div class="cardData"><%= text_area_tag(:photos, 'Provide a link to a page, forum post or online location with photos and video of the recipients affected limb.  A volunteer can help you take required photos once you have accepted their offer.', class: 'messageBox', style: 'height: 80px;') %></div></div>
		<div class="actions"><%= submit_tag "SUBMIT REQUEST", class: 'loginaction' %></div>
	</div>
	
	<% end %>
</div>


app/views/requests/show.html.erb
<div class="sectionHeader" style="margin-bottom: 0px;">Request</div>
	<div class="card" style="margin-bottom: 10px; cursor: default; display: block;">
		<div class="cardLine"><div class="cardHead">Request ID #</div><div class="cardData"><%= @request.id %></div></div>
		<div class="cardLine"><div class="cardHead">Request Date</div><div class="cardData"> <%= @request.created_at.strftime('%x') %></div></div>
		<div class="cardLine"><div class="cardHead">Requested By</div><div class="cardData"> <%= link_to(Member.find(@request.member_id).full_name, url_for(Member.find(@request.member_id))) %></div></div>
		<div class="cardLine"><div class="cardHead">Device</div><div class="cardData"> <%= link_to(Device.find(@request.device_id).title, url_for(Device.find(@request.device_id))) %></div></div>
		<div class="cardLine"><div class="cardHead">Side</div><div class="cardData"> <%= @request.side %></div></div>
		<div class="cardLine"><div class="cardHead">Stage</div><div class="cardData"> <%= @request.stage %></div></div>
		<div class="cardLine"><div class="cardHead">Measurements</div><div class="cardData"> <%= @request.measurements %></div></div>
		<div class="cardLine"><div class="cardHead">Photos</div><div class="cardData"> <%= @request.photos %></div></div>
		<div class="cardLine"><div class="cardHead">Colors</div><div class="cardData"> <%= @request.colors %></div></div>
		<% if (current_member.id == @request.member_id) || @request.accepted_offer(current_member) || current_member.admin? %>
			<div class="cardLine"><div class="cardHead">Shipping Address</div><div class="cardData"> <%= @request.shipping_address %>
			<div id="map" style='min-width: 100px; min-height: 100px; max-height: 100px; max-width: 200px; margin-bottom: 10px; margin-right: 20px;'></div></div></div>
			<div class="cardLine"><div class="cardHead">Evidence of Completion</div><div class="cardData"> <%= if @request.evidence; @request.evidence; else; 'None'; end; %></div></div>
		<% end %>
	</div>

	<div style="margin-top: 10px; margin-bottom: 35px;">
		<% if (@request.member_id == current_member.id || current_member.admin?) && @request.stage != "Completed" %>
			<div>
			<%= link_to("EDIT REQUEST", edit_request_path(@request), method: "GET", class: "loginaction") %>
			<%= link_to("COMPLETE REQUEST", url_for(controller: 'requests', action: "complete", id: @request.id), class: "loginaction") %>
			</div>
		<% end %>
		<% if @match && @request.member_id != current_member.id && !@request.open_offer(current_member) && @request.stage == "Open" %>
			<%= link_to("OFFER TO HELP", new_offer_path<<"?request_id="<<@request.id.to_s, class: "loginaction") %>
		<% end %>
	</div>
</div>

<% if !@requests.nil? %> 
	<div class="sectionHeader" style="margin-bottom: 0;">Offers on this request</div>
	<% @offers = Offer.where(request_id: @request.id) %>
	<% if !@offers.empty? %>
		<%= render "layouts/offers" %>
	<% else %>
		<div class="zero"> None </div>
	<% end %>
<% end %>

<script>
  $(function(handler) {
    handler = Gmaps.build('Google');
    handler.buildMap({ 
    	provider: {
	    	maxZoom: 10, 
	    	mapTypeControl: false,
	    	streetViewControl: false,
	    	zoomControl: false},
	    internal: { id: 'map' } },
	  function(){
      markers = handler.addMarkers([
        {lat: <%= @request.latitude %>,
         lng: <%= @request.longitude %>}
      ]);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      handler.getMap().setZoom(3);
    });
  });
</script>