config/routes.rb
Rails.application.routes.draw do
  
  if !Rails.env.development?
    match "*path" => redirect("https://matching.e-nable.me/%{path}"), :constraints => { :protocol => "http://" }, :via => [:get, :post]
    match "*path" => redirect("https://matching.e-nable.me/%{path}"), :constraints => { :subdomain => "" }, :via => [:get, :post]
  end
  
  devise_for :members, controllers: {registrations: 'members/registrations', sessions: 'members/sessions'}

  devise_scope :member do
    root to: "devise/sessions#new"
    get "members/sign_out", to: 'devise/sessions#destroy'
    get "members/:id/edit", to: 'members/registrations#edit'
  end
    
  devise_scope :offer do
    post 'offers/:id/accept', to: 'offers#accept', as: 'offers_accept'
    post 'offers/:id/decline', to: 'offers#decline', as: 'offers_decline'
  end
    
  devise_scope :request do
    get 'requests/mine', to: 'requests#mine'
    get 'requests/:id/complete', to: 'requests#complete'
  end
  
  devise_scope :chapter do
    get 'chapters/:id/claim', to: 'chapters#claim'
    get 'chapters/:id/claimsend', to: 'chapters#claimsend'
    get 'chapters/agree', to: 'chapters#agree'
    get 'chapters/:id/review', to: 'chapters#review'
    post 'chapters/:id/approve', to: 'chapters#approve'
    post 'chapters/:id/reject', to: 'chapters#reject'
  end

  resources :members
  resources :requests
  resources :offers
  resources :devices
  resources :messages
  resources :chapters
  resources :notices
  resources :reviews

  get 'states/:country', to: 'application#states'
  get 'cities/:state', to: 'application#cities'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_chapter.html.erb
<div class="card" style="font-weight: <%= if @chapter.active?; 'normal'; else; 'bold'; end; %> ">
	<a href="<%= url_for(@chapter) %>">
		<div class="cardCol" style="min-width: 300px; max-width: 300px;"><%= @chapter.name %></div>
		<div class="cardCol"><%= if @chapter.lead != nil; Member.find(@chapter.lead).full_name; else; 'No Leader'; end; %></div>
		<div class="cardCol"><%= @chapter.active ? "Active" : "Inactive" %></div>
		<div class="cardCol" style="max-width: unset;"><%= @chapter.location %></div>
		<!--<div class="cardCol"><%= link_to("Claim Chapter", url_for(controller: 'chapters', action: 'claim', id: @chapter.id), class: "clicky") %></div>-->
	</a>
</div>


app/views/layouts/_chapters.html.erb
<% if !@chapters.empty? %>
	<div class="cardContainer">
	<% @chapters.each do |chapter| %>
		<% if chapter.active? || current_member.admin? %>
			<% @chapter = chapter %>
				<%= render "layouts/chapter"%>
		<% end %>
	<% end %>
	</div>
<% else %>
	<div class="zero"> None </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="sponsor" style="right: unset; text-align: left">
Please leave feedback <a href="https://docs.google.com/document/d/1DR8ULoQoJyhc5vQ0_5IvWzg-VW5g36QxV2GEwLAipEY/edit#" target="_new">here</a>
</div>
<div class="sponsor">
Sponsored by <a href="www.enableoutreach.org" target="_new">Enable Outreach</a>
</div>

<!-- For debugging -->
<% if current_member && current_member.admin? && Rails.env.development? %>
	<% console %>
<% end %>

app/views/layouts/_header.html.erb
<%= render "layouts/notice" %>

<% if member_signed_in? %>
  	<div class="menu">
		<%= render "layouts/menu" %>  
	</div>
	
	<hr style="border-color: rgb(89,210,255);">	  
<% end %>

app/views/layouts/_menu.html.erb
<% if current_member then %>
	<div class="menutab"><%= link_to "Dashboard", url_for(current_member) %></div>
	<div class="menutab"><%= link_to "Requests", requests_path %></div>
	<div class="menutab"><%= link_to "Chapters", chapters_path %></div>
	<div class="menutab" style="float: right;"><%= link_to('Logout', destroy_member_session_path, :method => :delete) %></div>
	<% unread = Message.all.where(to: current_member.id, status: "Unread").length %>
	<div class="menutab messageNotice">		
		<a href="<%= messages_path %>">
			<% if unread > 0 %>
				<style>
					.messageNotice a {color: red;}
				</style>
				<img src="/sendUnread.png" />
			<% else %>
				<img src="/send24X24.png" />
			<% end %>
		<%= unread %>
		</a>
	</div>
	<div class="menutab" style="float: right; margin-right: 5em;"><a href="http://enableoutreach.cloud.answerhub.com" target="_new">Q&A Site</a></div>
<% end %>

app/views/layouts/_message.html.erb
<div class="card" style="font-weight: <%= if @message.status == 'Unread'; 'bold'; else; 'normal'; end; %> ">
	<a href="<%= url_for(@message) %>">
		<div class="cardCol" style="min-width: 200px; max-width: 200px;"><%= Member.find(@message.from).full_name%> &#8594; <%= Member.find(@message.to).full_name %> </div>
		<div class="cardCol"><%= @message.created_at.strftime("%b %d, %I:%M") %></div>
		<div class="cardCol" style="max-width: unset;"><%= ActionView::Base.full_sanitizer.sanitize(@message.content) %></div>
	</a>
</div>

app/views/layouts/_messages.html.erb
<div class="messagesContainer">
	<% @messages.each do |message| %>
		<% @message = message %>
		<%= render "layouts/message" %>
	<% end %>
</div>

app/views/layouts/_notice.html.erb
<% if member_signed_in? %>
	<p id="notice"><%= notice %></p>
<% end %>

app/views/layouts/_offer.html.erb
<div class="card">
	<a href="<%= url_for(@offer) %>">
		<div class="cardCol" style="min-width: 250px; max-width: 250px;"><%= Member.find(@offer.member_id).full_name %> &#8594; <%= Member.find(@request.member_id).full_name %></div>
		<div class="cardCol"><%= @offer.updated_at.strftime('%x') %> </div>
		<div class="cardCol"><%= @offer.stage %> </div>
	</a>
</div>

app/views/layouts/_offers.html.erb
<% if !@offers.empty? %>
	<div style="position: relative; overflow: hidden;">
		<div class="cardContainer">
			<% @offers.each do |off| %>
				<% @offer = off %>
				<% @request = Request.find(off.request_id)%>
				<tr>
					<td>
						<%= render "layouts/offer"%>
					</td>
				</tr>
			<% end %>
		</div>
	</div>
<% else %>
	<div class="zero"> None </div>
<% end %>

app/views/layouts/_profile.html.erb
<div style="display: flex; position: relative; padding-left: 10px;">
  <div style="vertical-align: top; margin-right: 20px;">
	Name: <%=@member.full_name%><br />
	<% if @member==current_member %>
		Email: <%=@member.email%><br />
	<% end %>
	City: <%=@member.city%><br />
	State: <%=@member.state%><br />
	Country: <%=@member.country%><br />
  </div>	
  
  <% if params[:action] != "edit" && (@member.id == current_member.id || current_member.admin?) %>
  	<%= link_to('Edit profile', edit_member_path(@member), {:style=>'position:absolute;bottom:0;'}) %><br />
  <% end %>
   
  <div id="map" style='min-width: 100px; min-height: 100px; margin-bottom: 10px; margin-right: 20px;'></div>

  <% badges = @member.load_badges %>
  <% if !badges.nil? %>
	  <a href="https://credly.com/u/enablethefuture" target="_new">
	  	<div class="badgeContainer">
		  	<% badges.each do |badge| %>
		  		<img class="badgeImage" src='<%=badge['image']%>'>
		  	<% end %>
  		</div>
  	  </a>
  <% end %>
</div>

<script>
  $(function(handler) {
    handler = Gmaps.build('Google');
    handler.buildMap({ 
    	provider: {
	    	maxZoom: 10, 
	    	mapTypeControl: false,
	    	streetViewControl: false,
	    	zoomControl: false},
	    internal: { id: 'map' } },
	  function(){
      markers = handler.addMarkers([
        {lat: <%= @member.latitude %>,
         lng: <%= @member.longitude %>}
      ]);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      handler.getMap().setZoom(3);
    });
  });
</script>

app/views/layouts/_request.html.erb
<div class="card" style="font-weight: <%= if @request.stage == 'Open'; 'bold'; else; 'normal'; end; %> ">
	<a href="<%= url_for(@request) %>">
		<div class="cardCol">
			<% if @request.stage != 'Completed' %>
				<%= (Time.now.to_i - @request.created_at.to_i) /(60*60*24) %> days old
			<% end %>
		</div>
		<div class="cardCol" style="min-width: 150px; max-width: 150px;"><%= Member.find(@request.member_id).full_name %></div>
		<div class="cardCol" style="min-width: 150px; max-width: 150px;"><%= Device.find(@request.device_id).title %></div>
		<div class="cardCol"><%= @request.stage %></div>
		<% place=Geocoder.search(@request.latitude.to_s<<","<<@request.longitude.to_s)[0] %>
		<div class="cardCol" style="min-width: 150px; max-width: 100%;"><%= place.city%>, <%= if place.state; place.state; else; place.country; end; %></div>
		<% if @offer = @request.open_offer(current_member) %>
			<div class="cardCol"><%= link_to("Your Offer", Offer.where(member_id: current_member.id, request_id: @request.id)[0]) %></div>
		<% else %>
			<% if @match && @request.member_id != current_member.id && @request.stage == "Open" %>
				<div class="cardCol">
					<%= link_to("Offer to Help", new_offer_path<<"?request_id="<<@request.id.to_s) %>
				</div>
			<% end %>
		<% end %>
	</a>
</div>

app/views/layouts/_requests.html.erb
<% if !@requests.empty? %>
	<div style="position: relative; overflow: hidden;">
		<div class="cardContainer">
			<% @requests.each do |req| %>
				<% @request = req %>
				<% @offers = Offer.where(request_id: req.id) %>
					<%= render "layouts/request" %>
			<% end %>
		</div>
	</div>
<% else %>
	<div class="zero"> None </div>
<% end %>

app/views/layouts/_respond.html.erb
<div>
	<%= form_tag(messages_path) do %>
	<%= hidden_field_tag "message[to]", @message.from %>
	<%= hidden_field_tag "message[from]", current_member.id %>
	
	<div class="card" style="margin-bottom: 10px; cursor: default; display: block;">
		<div class="cardLine"><div class="cardHead">From</div><div class="cardData"><%= current_member.first_name %></div></div>
		<div class="cardLine"><div class="cardHead">To</div><div class="cardData"><%= Member.find(@message.from).first_name %></div></div>
		<div class="cardLine"><div class="cardHead">Message</div><div class="cardData"> <%= text_area_tag("message[content]", "", class: "messageBox") %></div></div>
		<div class="actions"><%= submit_tag "Send", class: 'clicky'%></div>
	</div>
	
	<% end %>
</div>